export const PRODUCT_REQUEST = "PRODUCTS_LIST_REQUEST";
export const PRODUCT_REQUEST_SUCCESS = "PRODUCTS_LIST_SUCCESS";
export const PRODUCT_REQUEST_FAILURE = "PRODUCTS_LIST_FAILURE";

export const PRODUCT_DETAILS_REQUEST = "PRODUCTS_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCTS_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAILURE = "PRODUCTS_DETAILS_FAILURE";
export const CLEAR_PRODUCT_DETAILS = "CLEAR_PRODUCT_DETAILS";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_CREATE";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";
