export const PRODUCT_REQUEST = 'PRODUCTS_LIST_REQUEST';
export const PRODUCT_REQUEST_SUCCESS = 'PRODUCTS_LIST_SUCCESS';
export const PRODUCT_REQUEST_FAILURE = 'PRODUCTS_LIST_FAILURE';


export const PRODUCT_DETAILS_REQUEST = 'PRODUCTS_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCTS_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAILURE = 'PRODUCTS_DETAILS_FAILURE';
export const CLEAR_PRODUCT_DETAILS = 'CLEAR_PRODUCT_DETAILS';
