export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const CREATE_ORDER_DETAILS_SUCCESS = "CREATE_ORDER_DETAILS_SUCCESS";
export const CREATE_ORDER_DETAILS_REQUEST = "CREATE_ORDER_DETAILS_REQUEST";
export const CREATE_ORDER_DETAILS_FAILURE = "CREATE_ORDER_DETAILS_FAILURE";
export const ORDER_DETAILS_RESET = "ORDER_DETAILS_RESET";

export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_FAILURE = "ORDER_PAY_FAILURE";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_LIST_MY_REQUEST_SUCCESS = "ORDER_LIST_MY_REQUEST_SUCCESS";
export const ORDER_LIST_MY_REQUEST_REQUEST = "ORDER_LIST_MY_REQUEST_REQUEST";
export const ORDER_LIST_MY_REQUEST_FAILURE = "ORDER_LIST_MY_REQUEST_FAILURE";
export const ORDER_LIST_MY_RESET = "ORDER_LIST_MY_RESET";
